// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBft8R-WImGy5pDglqj0TK-l6GEa93mNa4',
    appId: '1:639036879009:web:cc7ef84f13fb103041c0e0',
    messagingSenderId: '639036879009',
    projectId: 'vantrek-rides',
    authDomain: 'vantrek-rides.firebaseapp.com',
    storageBucket: 'vantrek-rides.firebasestorage.app',
    measurementId: 'G-0ENTDYL2XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3xtakqka9t5QfeAwgHhxpf7gGeOnq48s',
    appId: '1:639036879009:android:9b72216a4d911f9a41c0e0',
    messagingSenderId: '639036879009',
    projectId: 'vantrek-rides',
    storageBucket: 'vantrek-rides.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vbvW5F8wigLXngjYElaYdIwccuFacSM',
    appId: '1:639036879009:ios:d81dc1af83bef72341c0e0',
    messagingSenderId: '639036879009',
    projectId: 'vantrek-rides',
    storageBucket: 'vantrek-rides.firebasestorage.app',
    iosBundleId: 'com.vanrek.vantrekRides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vbvW5F8wigLXngjYElaYdIwccuFacSM',
    appId: '1:639036879009:ios:d81dc1af83bef72341c0e0',
    messagingSenderId: '639036879009',
    projectId: 'vantrek-rides',
    storageBucket: 'vantrek-rides.firebasestorage.app',
    iosBundleId: 'com.vanrek.vantrekRides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBft8R-WImGy5pDglqj0TK-l6GEa93mNa4',
    appId: '1:639036879009:web:841b9e7c9539a3cc41c0e0',
    messagingSenderId: '639036879009',
    projectId: 'vantrek-rides',
    authDomain: 'vantrek-rides.firebaseapp.com',
    storageBucket: 'vantrek-rides.firebasestorage.app',
    measurementId: 'G-8VS7V0KQSH',
  );
}
